[tool.black]
line-length = 79
target-version = ["py311"]

[tool.isort]
line_length = 79
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
split_on_trailing_comma = true